name: StyLua

on:
  push:
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install StyLua
        run: |
          curl -sL "https://github.com/JohnnyMorganz/StyLua/releases/download/v2.4.1/stylua-linux-x86_64.zip" -o stylua.zip
          unzip stylua.zip
      - name: Check formatting
        run: ./stylua --check .
